version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: node-container
    hostname: node-container
    restart: always
    tty: true
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/usersdb
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
    container_name: next-container
    hostname: next-container
    restart: always
    tty: true
    ports:
      - "3000:3000"
    environment:
      NEXT_NODE_ENV: production
      NEXT_PUBLIC_API_URL: localhost:5000
    depends_on:
      - backend
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27020:27017"
